services:
  regeny_scraper:
    build: .
    command: python webscraper_regeny.py
    env_file:
      - .env

 # mckenzie_scraper:
 #   build: .
  #  command: python webscraper_mckenzie.py
  #  env_file:
  #    - .env